name: github-merged-pr
description: Checks out the GitHub PR merge ref rather than the branch HEAD
author: https://github.com/stellargraph
requirements: []
configuration:
  properties:
    cd:
      type: string
  required: []
